version: '2.12.2'

services:
  catalog:
    build: catalog
    mem_limit: 256m
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  reviews:
    build: reviews
    mem_limit: 256m
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  interests:
    build: interests
    mem_limit: 256m
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  agregate:
    build: agregate
    mem_limit: 256m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
